// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/config/env';

const { supabaseUrl, supabaseAnonKey } = env;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase credentials are required to initialize the client.');
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
