// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/config/env';

const { supabaseUrl, supabaseAnonKey } = env;

const DISABLED_SUPABASE_MESSAGE =
  'Supabase is not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your environment.';

const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey);

const createDisabledSupabaseClient = (): SupabaseClient<Database> =>
  new Proxy({}, {
    get(_target, property: string | symbol) {
      throw new Error(`${DISABLED_SUPABASE_MESSAGE} Attempted to access "${String(property)}" on the disabled client.`);
    },
  }) as unknown as SupabaseClient<Database>;

const createSupabaseBrowserClient = (): SupabaseClient<Database> => {
  if (!isSupabaseConfigured) {
    console.warn(DISABLED_SUPABASE_MESSAGE);
    return createDisabledSupabaseClient();
  }

  return createClient<Database>(supabaseUrl, supabaseAnonKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createSupabaseBrowserClient();

export { isSupabaseConfigured };
